#pragma once

namespace DirID
{
	enum DIRECTION { UP, DOWN, LEFT, RIGHT, END };
}

namespace ObjectID
{
	enum OBJID { PLAYER, MAP_PLAYER, ATTACK, MUSHROOM, FLOWER, LEAF, COIN, 
		ENEMY_ATTACK, TURTLE_MONSTER, GUMBA_MONSTER, FLOWER_MONSTER, CIRCLE_MONSTER, BOSS,
		QUESTION_BOX, NOTE_BOX, BULLET, ENEMY_BULLET, OBSTACLE, 
		EFFECT, DOOR, FINAL_ITEM, FINAL_MSG, TITLE_NUMBER, TITLE_SELECT, END };
}

namespace LayerID
{
	enum ID { BACKGROUND, GAMEOBJECT, EFFECT, UI, ITEM, END };
}

namespace ItemID
{
	enum ID { FLOWER, LEAF, MUSHROOM, COIN, END };
}